<?php

namespace App\Http\Controllers;

use App\SoftwareType;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class SoftwareTypeController extends CrudControllerBase
{
    function __construct() {
        parent::__construct(SoftwareType::class, ['id', 'typename']);
    }

    protected function queryMany(Request $request, Builder $builder): Builder
    {
        return $builder->withCount('software'); // TODO: Change the autogenerated stub
    }
    protected function applyFilters(array $filter, Builder $builder): Builder
    {
        if(array_key_exists('software_count_low_bound', $filter)){
            $builder = $builder
                ->has('rooms', '>=', $filter['software_count_low_bound']);
        }

        if(array_key_exists('software_count_high_bound', $filter)){
            $builder = $builder
                ->has('rooms', '<=', $filter['software_count_high_bound']);
        }

        if(array_key_exists('category', $filter)){
            $builder = $builder->where('category', $filter['category']);
        }

        return $builder;
    }

}
