<?php

namespace App\Http\Controllers;

use App\SoftwareType;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class SoftwareTypeController extends CrudControllerBase
{
    function __construct() {
        parent::__construct(SoftwareType::class, ['id', 'typename']);
    }

    protected function queryMany(Request $request, Builder $builder): Builder
    {
        return parent::queryMany($request, $builder->withCount('software')); // TODO: Change the autogenerated stub
    }

}
